### ISSUE TITLE
意図しない検査

### ISSUE THREAD

**Issue by uchan-nos** [malony0/pbl.TODOServer#1]
https://github.com/malony0/pbl.TODOServer/blob/master/todoserver.py#L123

でor演算子を使って `(EVENT_KEY_DEADLINE or EVENT_KEY_TITLE) not in event_keys` というように書いていますが，おそらく意図しない挙動になっています．

Python で `"deadline" or "title"` の結果は `"deadline"` となりますので，上記の式は `EVENT_KEY_DEADLINE not in event_keys` と等価です．

やりたいのは `(EVENT_KEY_DEADLINE not in event_keys) or (EVENT_KEY_TITLE not in event_keys)` と思います．

**Comment by malony0** [comment]
うわあごめんなさい，今気が付きました．直します
ありがとうございます．
